/** Human labels for columns that appear in audit diffs. */
export const FIELD_LABELS: Record<string, string> = {
  name: "Name",
  hw_id: "HW ID",
  category_id: "Category",
  quantity: "Quantity",
  provider_id: "Given by / source",
  current_owner: "Current owner",
  status: "Status",
  received_date: "Received date",
  manufacturer: "Manufacturer",
  model: "Model",
  part_number: "Part number",
  serial_number: "Serial number",
  vendor_id: "Vendor",
  purchase_date: "Purchase date",
  unit_cost: "Unit cost",
  invoice_number: "Invoice number",
  warranty_expiry: "Warranty until",
  current_holder: "Current holder",
  location_id: "Location",
  project_id: "Project",
  description: "Description",
  specifications: "Specifications",
  notes: "Notes",
  archived_at: "Archived at",
  archived_by: "Archived by",
  is_active: "Active",
  full_name: "Full name",
  role: "Role",
  email: "Email",
  granted: "Granted",
  permission: "Permission",
  org_name: "Organization name",
  currency: "Currency",
  warranty_alert_days: "Warranty alert days",
  code: "Code",
  lead_name: "Lead",
  start_date: "Start date",
  end_date: "End date",
  provider_type: "Type",
  contact_name: "Contact",
  phone: "Phone",
  website: "Website",
  address: "Address",
  tax_id: "Tax ID",
  building: "Building",
  room: "Room",
  kind: "File type",
  file_name: "File name",
  storage_path: "Storage path",
  size_bytes: "Size",
  mime_type: "MIME type",
};

export function fieldLabel(key: string) {
  return FIELD_LABELS[key] ?? key.replace(/_/g, " ").replace(/^\w/, (c) => c.toUpperCase());
}
